### ISSUE TITLE
New ideas

### ISSUE THREAD

**Issue by Htepple** [LucGamesYT/MoreFeatures#1] opened 2019-08-07 12:32 UTC
I think you can try to add totem or enchantment table + anvil. :3

**Comment by LucGamesYT** [comment] 2019-08-07 12:39
enchantment and anvil works in nukkit. But the totem is a good idea!

**Comment by Htepple** [comment] 2019-08-07 13:18
Anvil in nukkit has a lot of bugs, for example items disappearing.

**Comment by Htepple** [comment] 2019-08-07 13:19
or "endless" experience.

**Comment by NycuRO** [comment] 2019-08-08 14:06
@LucGamesYT  Anvil and Enchantment table not works. It's just packets added without check. Have a lot of bugs like duplication and there's no check/handle server properly.

**Comment by LucGamesYT** [comment] 2019-08-09 08:37
Enchantment Table is fixed in the newest Nukkit version. But I can sit on the Anvil.

**Comment by LucGamesYT** [comment] 2019-08-09 08:40
@Htepple The bug with the infinite experience I can not produce after.
And I can't reproduce the disappearance either.

**Closed** 2019-08-16 10:22 UTC
